[package]
name = "edhoc-ead"
version = "0.1.0"
edition = "2021"
authors = ["Geovane Fedrecheski <geonnave@gmail.com>"]
license = "BSD"
description = "EDHOC EAD library dispatch crate"

[dependencies]
edhoc-consts = { path = "../consts", version = "0.1.0", default-features = false }

edhoc-ead-none = { path = "./edhoc-ead-none", version = "0.1.0", optional = true }
edhoc-ead-zeroconf = { path = "./edhoc-ead-zeroconf", version = "0.1.0", optional = true }

[features]
default = [ "ead-none" ]
ead-none = [ "edhoc-ead-none" ]
ead-zeroconf = [ "edhoc-ead-zeroconf" ]
